# Generated by Django 6.0 on 2026-04-02 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab_tests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='labtest',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='labtest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='Pending', max_length=20),
        ),
    ]
