# Generated by Django 6.0 on 2026-04-02 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab_tests', '0002_labtest_created_at_alter_labtest_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labtest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
