# Generated by Django 6.0 on 2026-04-02 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab_tests', '0004_alter_labtest_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labtest',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
