# Generated by Django 6.0 on 2026-04-06 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prescriptions', '0002_prescription_date_prescription_doctor_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prescription',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='prescription',
            name='dosage',
            field=models.TextField(blank=True),
        ),
    ]
